# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'account_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import get_user_data_rpc_pb2 as get__user__data__rpc__pb2
import get_nex_password_rpc_pb2 as get__nex__password__rpc__pb2
import get_nex_data_rpc_pb2 as get__nex__data__rpc__pb2
import update_rnid_permissions_pb2 as update__rnid__permissions__pb2
import exchange_token_for_user_data_pb2 as exchange__token__for__user__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x63\x63ount_service.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17get_user_data_rpc.proto\x1a\x1aget_nex_password_rpc.proto\x1a\x16get_nex_data_rpc.proto\x1a\x1dupdate_rnid_permissions.proto\x1a\"exchange_token_for_user_data.proto2\xb3\x03\n\x07\x41\x63\x63ount\x12J\n\x0bGetUserData\x12\x1b.account.GetUserDataRequest\x1a\x1c.account.GetUserDataResponse\"\x00\x12S\n\x0eGetNEXPassword\x12\x1e.account.GetNEXPasswordRequest\x1a\x1f.account.GetNEXPasswordResponse\"\x00\x12G\n\nGetNEXData\x12\x1a.account.GetNEXDataRequest\x1a\x1b.account.GetNEXDataResponse\"\x00\x12X\n\x15UpdateRNIDPermissions\x12%.account.UpdateRNIDPermissionsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x64\n\x18\x45xchangeTokenForUserData\x12(.account.ExchangeTokenForUserDataRequest\x1a\x1c.account.GetUserDataResponse\"\x00\x42\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_ACCOUNT']._serialized_start=208
  _globals['_ACCOUNT']._serialized_end=643
# @@protoc_insertion_point(module_scope)
