# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_user_data_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'get_user_data_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mii_pb2 as mii__pb2
import rnid_permission_flags_pb2 as rnid__permission__flags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17get_user_data_rpc.proto\x12\x07\x61\x63\x63ount\x1a\tmii.proto\x1a\x1brnid_permission_flags.proto\"!\n\x12GetUserDataRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\"\xcd\x02\n\x13GetUserDataResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x04 \x01(\x05\x12\x1b\n\x13server_access_level\x18\x05 \x01(\t\x12\x19\n\x03mii\x18\x06 \x01(\x0b\x32\x0c.account.Mii\x12\x15\n\rcreation_date\x18\x07 \x01(\t\x12\x11\n\tbirthdate\x18\x08 \x01(\t\x12\x0e\n\x06gender\x18\t \x01(\t\x12\x0f\n\x07\x63ountry\x18\n \x01(\t\x12\x10\n\x08language\x18\x0b \x01(\t\x12\x15\n\remail_address\x18\x0c \x01(\t\x12\x11\n\ttier_name\x18\r \x01(\t\x12\x31\n\x0bpermissions\x18\x0e \x01(\x0b\x32\x1c.account.RNIDPermissionFlagsB\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_user_data_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_GETUSERDATAREQUEST']._serialized_start=76
  _globals['_GETUSERDATAREQUEST']._serialized_end=109
  _globals['_GETUSERDATARESPONSE']._serialized_start=112
  _globals['_GETUSERDATARESPONSE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
