# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_nex_data_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'get_nex_data_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16get_nex_data_rpc.proto\x12\x07\x61\x63\x63ount\" \n\x11GetNEXDataRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\"\xb9\x01\n\x12GetNEXDataResponse\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nowning_pid\x18\x03 \x01(\r\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x04 \x01(\x05\x12\x1b\n\x13server_access_level\x18\x05 \x01(\t\x12\x13\n\x0b\x66riend_code\x18\x06 \x01(\t\x12(\n\x0b\x64\x65vice_type\x18\x07 \x01(\x0e\x32\x13.account.DeviceType*\x1e\n\nDeviceType\x12\x07\n\x03\x43TR\x10\x00\x12\x07\n\x03WUP\x10\x01\x42\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_nex_data_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_DEVICETYPE']._serialized_start=257
  _globals['_DEVICETYPE']._serialized_end=287
  _globals['_GETNEXDATAREQUEST']._serialized_start=35
  _globals['_GETNEXDATAREQUEST']._serialized_end=67
  _globals['_GETNEXDATARESPONSE']._serialized_start=70
  _globals['_GETNEXDATARESPONSE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
