# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_nex_password_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'get_nex_password_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aget_nex_password_rpc.proto\x12\x07\x61\x63\x63ount\"$\n\x15GetNEXPasswordRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\"*\n\x16GetNEXPasswordResponse\x12\x10\n\x08password\x18\x01 \x01(\tB\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_nex_password_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_GETNEXPASSWORDREQUEST']._serialized_start=39
  _globals['_GETNEXPASSWORDREQUEST']._serialized_end=75
  _globals['_GETNEXPASSWORDRESPONSE']._serialized_start=77
  _globals['_GETNEXPASSWORDRESPONSE']._serialized_end=119
# @@protoc_insertion_point(module_scope)
