# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rnid_permission_flags.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rnid_permission_flags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brnid_permission_flags.proto\x12\x07\x61\x63\x63ount\"\xe1\x04\n\x13RNIDPermissionFlags\x12\x1e\n\x16\x62\x61nned_all_permanently\x18\x01 \x01(\x08\x12\x1e\n\x16\x62\x61nned_all_temporarily\x18\x02 \x01(\x08\x12\x13\n\x0b\x62\x65ta_access\x18\x03 \x01(\x08\x12\x1a\n\x12\x61\x63\x63\x65ss_admin_panel\x18\x04 \x01(\x08\x12\x1d\n\x15\x63reate_server_configs\x18\x05 \x01(\x08\x12\x1d\n\x15modify_server_configs\x18\x06 \x01(\x08\x12\x15\n\rdeploy_server\x18\x07 \x01(\x08\x12\x14\n\x0cmodify_rnids\x18\x08 \x01(\x08\x12\x1b\n\x13modify_nex_accounts\x18\t \x01(\x08\x12\x17\n\x0fmodify_consoles\x18\n \x01(\x08\x12\x11\n\tban_rnids\x18\x0b \x01(\x08\x12\x18\n\x10\x62\x61n_nex_accounts\x18\x0c \x01(\x08\x12\x14\n\x0c\x62\x61n_consoles\x18\r \x01(\x08\x12\x19\n\x11moderate_miiverse\x18\x0e \x01(\x08\x12\x17\n\x0f\x63reate_api_keys\x18\x0f \x01(\x08\x12\x19\n\x11\x63reate_boss_tasks\x18\x10 \x01(\x08\x12\x19\n\x11update_boss_tasks\x18\x11 \x01(\x08\x12\x19\n\x11\x64\x65lete_boss_tasks\x18\x12 \x01(\x08\x12\x19\n\x11upload_boss_files\x18\x13 \x01(\x08\x12\x19\n\x11update_boss_files\x18\x14 \x01(\x08\x12\x19\n\x11\x64\x65lete_boss_files\x18\x15 \x01(\x08\x12\x1f\n\x17update_rnid_permissions\x18\x16 \x01(\x08\x42\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rnid_permission_flags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_RNIDPERMISSIONFLAGS']._serialized_start=41
  _globals['_RNIDPERMISSIONFLAGS']._serialized_end=650
# @@protoc_insertion_point(module_scope)
