# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: update_rnid_permissions.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'update_rnid_permissions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rnid_permission_flags_pb2 as rnid__permission__flags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dupdate_rnid_permissions.proto\x12\x07\x61\x63\x63ount\x1a\x1brnid_permission_flags.proto\"^\n\x1cUpdateRNIDPermissionsRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x31\n\x0bpermissions\x18\x02 \x01(\x0b\x32\x1c.account.RNIDPermissionFlagsB\x11Z\x0f./;grpc_accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_rnid_permissions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_account'
  _globals['_UPDATERNIDPERMISSIONSREQUEST']._serialized_start=71
  _globals['_UPDATERNIDPERMISSIONSREQUEST']._serialized_end=165
# @@protoc_insertion_point(module_scope)
