# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accept_friend_request_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'accept_friend_request_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61\x63\x63\x65pt_friend_request_rpc.proto\x12\x07\x66riends\"7\n\x1a\x41\x63\x63\x65ptFriendRequestRequest\x12\x19\n\x11\x66riend_request_id\x18\x01 \x01(\x04\".\n\x1b\x41\x63\x63\x65ptFriendRequestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42\x11Z\x0f./;grpc_friendsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accept_friend_request_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./;grpc_friends'
  _globals['_ACCEPTFRIENDREQUESTREQUEST']._serialized_start=44
  _globals['_ACCEPTFRIENDREQUESTREQUEST']._serialized_end=99
  _globals['_ACCEPTFRIENDREQUESTRESPONSE']._serialized_start=101
  _globals['_ACCEPTFRIENDREQUESTRESPONSE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
