# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deny_friend_request_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64\x65ny_friend_request_rpc.proto\x12\x07\x66riends\"5\n\x18\x44\x65nyFriendRequestRequest\x12\x19\n\x11\x66riend_request_id\x18\x01 \x01(\x04\",\n\x19\x44\x65nyFriendRequestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42\x11Z\x0f./;grpc_friendsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deny_friend_request_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./;grpc_friends'
  _DENYFRIENDREQUESTREQUEST._serialized_start=42
  _DENYFRIENDREQUESTREQUEST._serialized_end=95
  _DENYFRIENDREQUESTRESPONSE._serialized_start=97
  _DENYFRIENDREQUESTRESPONSE._serialized_end=141
# @@protoc_insertion_point(module_scope)
