# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friends_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import send_user_notification_wiiu_rpc_pb2 as send__user__notification__wiiu__rpc__pb2
from . import get_user_friend_pids_rpc_pb2 as get__user__friend__pids__rpc__pb2
from . import send_user_friend_request_rpc_pb2 as send__user__friend__request__rpc__pb2
from . import get_user_friend_requests_incoming_rpc_pb2 as get__user__friend__requests__incoming__rpc__pb2
from . import accept_friend_request_rpc_pb2 as accept__friend__request__rpc__pb2
from . import deny_friend_request_rpc_pb2 as deny__friend__request__rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66riends_service.proto\x12\x07\x66riends\x1a\x1bgoogle/protobuf/empty.proto\x1a%send_user_notification_wiiu_rpc.proto\x1a\x1eget_user_friend_pids_rpc.proto\x1a\"send_user_friend_request_rpc.proto\x1a+get_user_friend_requests_incoming_rpc.proto\x1a\x1f\x61\x63\x63\x65pt_friend_request_rpc.proto\x1a\x1d\x64\x65ny_friend_request_rpc.proto2\xf6\x04\n\x07\x46riends\x12^\n\x18SendUserNotificationWiiU\x12(.friends.SendUserNotificationWiiURequest\x1a\x16.google.protobuf.Empty\"\x00\x12\\\n\x11GetUserFriendPIDs\x12!.friends.GetUserFriendPIDsRequest\x1a\".friends.GetUserFriendPIDsResponse\"\x00\x12h\n\x15SendUserFriendRequest\x12%.friends.SendUserFriendRequestRequest\x1a&.friends.SendUserFriendRequestResponse\"\x00\x12\x80\x01\n\x1dGetUserFriendRequestsIncoming\x12-.friends.GetUserFriendRequestsIncomingRequest\x1a..friends.GetUserFriendRequestsIncomingResponse\"\x00\x12\x62\n\x13\x41\x63\x63\x65ptFriendRequest\x12#.friends.AcceptFriendRequestRequest\x1a$.friends.AcceptFriendRequestResponse\"\x00\x12\\\n\x11\x44\x65nyFriendRequest\x12!.friends.DenyFriendRequestRequest\x1a\".friends.DenyFriendRequestResponse\"\x00\x42\x11Z\x0f./;grpc_friendsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'friends_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./;grpc_friends'
  _FRIENDS._serialized_start=280
  _FRIENDS._serialized_end=910
# @@protoc_insertion_point(module_scope)
