# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_user_friend_pids_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eget_user_friend_pids_rpc.proto\x12\x07\x66riends\"\'\n\x18GetUserFriendPIDsRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\")\n\x19GetUserFriendPIDsResponse\x12\x0c\n\x04pids\x18\x01 \x03(\rB\x11Z\x0f./;grpc_friendsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_user_friend_pids_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./;grpc_friends'
  _GETUSERFRIENDPIDSREQUEST._serialized_start=43
  _GETUSERFRIENDPIDSREQUEST._serialized_end=82
  _GETUSERFRIENDPIDSRESPONSE._serialized_start=84
  _GETUSERFRIENDPIDSRESPONSE._serialized_end=125
# @@protoc_insertion_point(module_scope)
