# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_user_friend_requests_incoming_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import friend_request_pb2 as friend__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+get_user_friend_requests_incoming_rpc.proto\x12\x07\x66riends\x1a\x14\x66riend_request.proto\"3\n$GetUserFriendRequestsIncomingRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\"X\n%GetUserFriendRequestsIncomingResponse\x12/\n\x0f\x66riend_requests\x18\x01 \x03(\x0b\x32\x16.friends.FriendRequestB\x11Z\x0f./;grpc_friendsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_user_friend_requests_incoming_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./;grpc_friends'
  _GETUSERFRIENDREQUESTSINCOMINGREQUEST._serialized_start=78
  _GETUSERFRIENDREQUESTSINCOMINGREQUEST._serialized_end=129
  _GETUSERFRIENDREQUESTSINCOMINGRESPONSE._serialized_start=131
  _GETUSERFRIENDREQUESTSINCOMINGRESPONSE._serialized_end=219
# @@protoc_insertion_point(module_scope)
