# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miiverse_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'miiverse_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import smm_request_post_id_rpc_pb2 as smm__request__post__id__rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16miiverse_service.proto\x12\x08miiverse\x1a\x1dsmm_request_post_id_rpc.proto2g\n\x08Miiverse\x12[\n\x10SMMRequestPostId\x12!.miiverse.SMMRequestPostIDRequest\x1a\".miiverse.SMMRequestPostIDResponse\"\x00\x42\x12Z\x10./;grpc_miiverseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miiverse_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./;grpc_miiverse'
  _globals['_MIIVERSE']._serialized_start=67
  _globals['_MIIVERSE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
