# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smm_request_post_id_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'smm_request_post_id_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsmm_request_post_id_rpc.proto\x12\x08miiverse\",\n\x17SMMRequestPostIDRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x04\"+\n\x18SMMRequestPostIDResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x42\x12Z\x10./;grpc_miiverseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smm_request_post_id_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./;grpc_miiverse'
  _globals['_SMMREQUESTPOSTIDREQUEST']._serialized_start=43
  _globals['_SMMREQUESTPOSTIDREQUEST']._serialized_end=87
  _globals['_SMMREQUESTPOSTIDRESPONSE']._serialized_start=89
  _globals['_SMMREQUESTPOSTIDRESPONSE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
