# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smm_request_post_id_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsmm_request_post_id_rpc.proto\x12\x08miiverse\",\n\x17SMMRequestPostIdRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x04\"+\n\x18SMMRequestPostIdResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x42\x12Z\x10./;grpc_miiverseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smm_request_post_id_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020./;grpc_miiverse'
  _SMMREQUESTPOSTIDREQUEST._serialized_start=43
  _SMMREQUESTPOSTIDREQUEST._serialized_end=87
  _SMMREQUESTPOSTIDRESPONSE._serialized_start=89
  _SMMREQUESTPOSTIDRESPONSE._serialized_end=132
# @@protoc_insertion_point(module_scope)
