# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_user_data_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'get_user_data_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mii_pb2 as mii__pb2
import user_connections_pb2 as user__connections__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17get_user_data_rpc.proto\x12\x03\x61pi\x1a\tmii.proto\x1a\x16user_connections.proto\"\xed\x02\n\x13GetUserDataResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x15\n\rcreation_date\x18\x02 \x01(\t\x12\x14\n\x0cupdated_date\x18\x03 \x01(\t\x12\x0b\n\x03pid\x18\x04 \x01(\r\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_level\x18\x06 \x01(\x05\x12\x1b\n\x13server_access_level\x18\x07 \x01(\t\x12\x15\n\x03mii\x18\x08 \x01(\x0b\x32\x08.api.Mii\x12\x10\n\x08\x62irthday\x18\t \x01(\t\x12\x0e\n\x06gender\x18\n \x01(\t\x12\x0f\n\x07\x63ountry\x18\x0b \x01(\t\x12\x10\n\x08timezone\x18\x0c \x01(\t\x12\x10\n\x08language\x18\r \x01(\t\x12\x15\n\remail_address\x18\x0e \x01(\t\x12)\n\x0b\x63onnections\x18\x0f \x01(\x0b\x32\x14.api.UserConnections\x12\x16\n\x0emarketing_flag\x18\x10 \x01(\x08\x42\rZ\x0b./;grpc_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_user_data_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./;grpc_api'
  _globals['_GETUSERDATARESPONSE']._serialized_start=68
  _globals['_GETUSERDATARESPONSE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
