# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogin_rpc.proto\x12\x03\x61pi\"\x98\x01\n\x0cLoginRequest\x12\x12\n\ngrant_type\x18\x01 \x01(\t\x12\x15\n\x08username\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08password\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rrefresh_token\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x0b\n\t_usernameB\x0b\n\t_passwordB\x10\n\x0e_refresh_token\"d\n\rLoginResponse\x12\x12\n\nexpires_in\x18\x01 \x01(\r\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\tB\rZ\x0b./;grpc_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;grpc_api'
  _LOGINREQUEST._serialized_start=25
  _LOGINREQUEST._serialized_end=177
  _LOGINRESPONSE._serialized_start=179
  _LOGINRESPONSE._serialized_end=279
# @@protoc_insertion_point(module_scope)
