# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reset_password_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18reset_password_rpc.proto\x12\x03\x61pi\"Q\n\x14ResetPasswordRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x18\n\x10password_confirm\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\tB\rZ\x0b./;grpc_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reset_password_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;grpc_api'
  _RESETPASSWORDREQUEST._serialized_start=33
  _RESETPASSWORDREQUEST._serialized_end=114
# @@protoc_insertion_point(module_scope)
