# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: set_stripe_connection_data_rpc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'set_stripe_connection_data_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$set_stripe_connection_data_rpc.proto\x12\x03\x61pi\"\x81\x02\n\x1eSetStripeConnectionDataRequest\x12\x18\n\x0b\x63ustomer_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fsubscription_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08price_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\ntier_level\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x16\n\ttier_name\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x42\x0e\n\x0c_customer_idB\x12\n\x10_subscription_idB\x0b\n\t_price_idB\r\n\x0b_tier_levelB\x0c\n\n_tier_nameB\rZ\x0b./;grpc_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_stripe_connection_data_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./;grpc_api'
  _globals['_SETSTRIPECONNECTIONDATAREQUEST']._serialized_start=46
  _globals['_SETSTRIPECONNECTIONDATAREQUEST']._serialized_end=303
# @@protoc_insertion_point(module_scope)
