# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_discord_connection_data_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%set_discord_connection_data_rpc.proto\x12\x03\x61pi\"-\n\x1fSetDiscordConnectionDataRequest\x12\n\n\x02id\x18\x01 \x01(\tB\rZ\x0b./;grpc_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_discord_connection_data_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;grpc_api'
  _SETDISCORDCONNECTIONDATAREQUEST._serialized_start=46
  _SETDISCORDCONNECTIONDATAREQUEST._serialized_end=91
# @@protoc_insertion_point(module_scope)
