# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_stripe_connection_data_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$set_stripe_connection_data_rpc.proto\x12\x03\x61pi\"\xe7\x02\n\x1eSetStripeConnectionDataRequest\x12\x18\n\x0b\x63ustomer_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fsubscription_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08price_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\ntier_level\x18\x04 \x01(\rH\x03\x88\x01\x01\x12\x16\n\ttier_name\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x19\n\x0c\x61\x63\x63\x65ss_level\x18\x07 \x01(\rH\x05\x88\x01\x01\x12 \n\x13server_access_level\x18\x08 \x01(\tH\x06\x88\x01\x01\x42\x0e\n\x0c_customer_idB\x12\n\x10_subscription_idB\x0b\n\t_price_idB\r\n\x0b_tier_levelB\x0c\n\n_tier_nameB\x0f\n\r_access_levelB\x16\n\x14_server_access_levelB\rZ\x0b./;grpc_apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_stripe_connection_data_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;grpc_api'
  _SETSTRIPECONNECTIONDATAREQUEST._serialized_start=46
  _SETSTRIPECONNECTIONDATAREQUEST._serialized_end=405
# @@protoc_insertion_point(module_scope)
